#pragma warning disable 1591
namespace ILNumerics_Licensing {
    /// <summary>
    /// This type supports ILNumerics infrastructure. Do not edit the code!
    /// </summary>
    /// <remarks>This type is automatically generated by ILNumerics Ultimate VS. If you encounter problems compiling this file, make sure to reference ILNumerics.Core in your project!</remarks>
    
        // <- ILNumerics.Core is needed here!
    public partial class ILLicHelper_2447f6431a114ee79c591822b5e0fae9_ { public ILLicHelper_2447f6431a114ee79c591822b5e0fae9_() { System.ComponentModel.LicenseManager.Validate(typeof(ILLicHelper_2447f6431a114ee79c591822b5e0fae9_), this); } }
}